### ISSUE TITLE
Receving this error after registration

### ISSUE THREAD

**Issue by marmik57** [delaroy/AndroidFirbaseChat#1]
main
                                                                                       java.lang.NullPointerException
                                                                                           at com.smartwaysolutions.chatapplication.ui.adapters.UserListingRecyclerAdapter.onBindViewHolder(UserListingRecyclerAdapter.java:37)
                                                                                           at com.smartwaysolutions.chatapplication.ui.adapters.UserListingRecyclerAdapter.onBindViewHolder(UserListingRecyclerAdapter.java:15)
                                                                                           at android.support.v7.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:6356)
                                                                                           at android.support.v7.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:6389)
                                                                                           at android.support.v7.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:5335)
                                                                                           at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5598)
                                                                                           at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5440)
                                                                                           at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5436)
                                                                                           at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2224)
                                                                                           at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1551)
                                                                                           at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1511)
                                                                                           at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:595)
                                                                                           at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3583)
                                                                                           at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3312)
                                                                                           at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3844)
                                                                                           at android.view.View.layout(View.java:13836)
                                                                                           at android.view.ViewGroup.layout(ViewGroup.java:4380)
                                                                                           at android.support.v4.widget.SwipeRefreshLayout.onLayout(SwipeRefreshLayout.java:636)
                                                                                           at android.view.View.layout(View.java:13836)
                                                                                           at android.view.ViewGroup.layout(ViewGroup.java:4380)
                                                                                           at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
                                                                                           at android.view.View.layout(View.java:13836)
                                                                                           at android.view.ViewGroup.layout(ViewGroup.java:4380)
                                                                                           at android.support.v4.view.ViewPager.onLayout(ViewPager.java:1795)
                                                                                           at android.view.View.layout(View.java:13836)
                                                                                           at android.view.ViewGroup.layout(ViewGroup.java:4380)
                                                                                           at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1649)
                                                                                           at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1507)
                                                                                           at android.widget.LinearLayout.onLayout(LinearLayout.java:1420)
                                                                                           at android.view.View.layout(View.java:13836)
                                                                                           at android.view.ViewGroup.layout(ViewGroup.java:4380)
                                                                                           at android.support.design.widget.HeaderScrollingViewBehavior.layoutChild(HeaderScrollingViewBehavior.java:131)
                                                                                           at android.support.design.widget.ViewOffsetBehavior.onLayoutChild(ViewOffsetBehavior.java:42)
                                                                                           at android.support.design.widget.AppBarLayout$ScrollingViewBehavior.onLayoutChild(AppBarLayout.java:1391)
                                                                                           at android.support.design.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:870)
                                                                                           at android.view.View.layout(View.java:13836)
                                                                                           at android.view.ViewGroup.layout(ViewGroup.java:4380)
                                                                                           at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
                                                                                           at android.view.View.layout(View.java:13836)
                                                                                           at android.view.ViewGroup.layout(ViewGroup.java:4380)
                                                                                           at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1649)
                                                                                           at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1507)
                                                                                           at android.widget.LinearLayout.onLayout(LinearLayout.java:1420)
                                                                                           at android.view.View.layout(View.java:13836)
                                                                                           at android.view.ViewGroup.layout(ViewGroup.java:4380)
                                                                                           at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
                                                                                           at android.view.View.layout(View.java:13836)
                                                                                           at android.view.ViewGroup.layout(ViewGroup.java:4380)
                                                                                           at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1649)
                                                                                           at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1507)
                                                                                           at android.widget.LinearLayout.onLayout(LinearLayout.java:1420)
                                                                                           at android.view.View.layout(View.java:13836)
                                                                                           at android.view.ViewGroup.layout(ViewGroup.java:4380)
                                                                                           at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
                                                                                           at android.view.View.layout(View.java:13836)
                                                                                       	at android.view.ViewGroup.layout(ViewGroup.java:

**Comment by WaqasAzamKml** [comment]
The code i'm posting is not the optimal solution, but it'll handle this error.
Update your **onBindViewHolder** inside **UserListingRecyclerAdapter.java** file

```
@Override
    public void onBindViewHolder(ViewHolder holder, int position) {
        User user = mUsers.get(position);
        String alphabet;
        if(user.email!=null) {
            alphabet = user.email.substring(0, 1);
            holder.txtUsername.setText(user.email);
            holder.txtUserAlphabet.setText(alphabet);
        }
        else {
            alphabet = "n";
            holder.txtUsername.setText("null@null.com");
            holder.txtUserAlphabet.setText(alphabet);
        }

    }
```
